### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by M5oul** [c-geek/wotex#2]
When going on http://wotex.cgeek.fr/?to=Cywil&pending=on&mode=u2w:
```bash
TypeError: Cannot read property 'uid' of undefined
    at alimenteLignes (/home/cmaster/dev/wotex/index.js:428:25)
    at /home/cmaster/dev/wotex/index.js:116:21
    at next (native)
    at onFulfilled (/home/cmaster/dev/wotex/node_modules/co/index.js:65:19)
    at propagateAslWrapper (/home/cmaster/.config/yarn/global/node_modules/async-listener/index.js:421:23)
    at /home/cmaster/.config/yarn/global/node_modules/async-listener/index.js:458:70
```

**Comment by c-geek** [comment]
Noted, however it no more occurs right now.
